language: ruby
rvm:
- 2.2.2
before_script: gem install jekyll
script: jekyll build --destination out
notifications:
  flowdock:
    secure: "l+r/RXhjPsNZMhH4e/99hqTYX5FGewYsyKU8NQE0D+59MrqhCHO8LKt4AAb/mCCX2zVONji+z4M6HVCqn+Ypu6Ssv3YzgB8P/fqxnoYRbAcZU7DFTCAt9C3wmOrjAEbmb+OpzSYbiba2AyTkl7rEqtV07ByXlb36J3oaPD+tpzF90riWqvt0pNPtmGmEob005Qoiw9ilrKVkdPp9Jn4606Wfh9EzcArojAdtTyQmMetvQBVDf9PdUNipYNVTGcooXEek38RZ1eTur3bNf4MtG06nBiQ4AM8PC6TmSBoSPQ0o+vONHSnMwItGStNF2U/CXDqgniVujBeMmd5hvp0TJPgdawH0/K6hoc6lgMPV8rU633Uxs7zfJqSQIlZqJ9i3Z7eVjfDEWAYxs719/+NX1jpsc5Ew2moHrOqY4U28R3S6wtRdPzULDNy+VR+yLsjnN/EQlZ3yG2Mb8AQiwZ+lkmHdcMI7SuFGvq2ZHloFZj6gZ4KimeQwKshKRzyUNT02DnCN2H1Qiq1qvLLjHEpeV3SMv+Jx26BPDHNChPY7IwOsV4G4Kv/OD7o8IwfP7ps64WH52BZ9cyEIA96bTOiDeSkxhKfH5ii71hjwVAsCdQMVLROclxrpI6kWgGIYg6vbA/LzxwxhQGPMu0dP/k/uX4pEdoMdAKidoOQUjQ0wSG4="
deploy:
  provider: s3
  bucket: brokerages.stockflare.com
  skip_cleanup: true
  local-dir: out
  edge: true
  region: us-east-1
  endpoint: s3-us-east-1.amazonaws.com
  on:
    branch: master
  access_key_id:
    secure: "ehx+ytN43MLvdVMUnHKDdIfl0kum9kwJqfRYcAQM1lnm9/h45Y6oHwES12yXyJFc4wS0HQZtpXO7KuVg0GxpGUvrQiw9JvbYjMlyRrlJW6CNuARkSg63YIuguuD0LmcSbORFwDcx+x5H2ew4YusoxWmrvLcVNKRo4nDY+h9Ts3FOtQARiPUIGT3JhRuJl0/enufuowHryYlYWhpD3JVe7iqc+EBQ+F4B8Ub6Y0/8b0gbu2xvMLdg3oGZXWixbSrcNvrAai1x80VHqAisOIhdHC8y1umdrYhZtFOaHz9dPtlJ+YLbde8WYqO0Aj39oSMVKZXBma12ovxPrtHc9JtY7zluJ2WyaBZmoL8pv4W1Ka5VJ+18efIQ5Hb6fpCHle5kU1YIBES0BjEU3W1/TK/FlyRv/zWxReWaIOzccltmF70DNCw8jpiLIE38jFGH6+ypMAotJLiuG21Th1PLO/UtrxanNI/ux6/FJll4v8hdw45vovHIF9/OEMnzMfZYm4zmp9eH6HGWYvjPI2xLk4XSVbFiow6xx58XgiC5XMRBzn5Orw3aq12GM3KKzI1g7Sqp2rgdBK7p6v5xmsiAzls3gpXnV9iU642xYzwAZpMXUcJ0lW99JMzLRETHuvPF4co+ZsrSyHZbq3hFia8qT7V2TUnL+QhPYw+SFSMjLfouHbQ="
  secret_access_key:
    secure: "QERcvWDSLayl0TvO5CLjp/kcESavX1WkFFF5W6RTSjRwegElkC1P6IfU49417DEQvlZoa9aKOc542Wt9nGiMJp4wpr6khRpHIXY3gIxVoPA6s+FTUbie9c2LJBUM8f5e3gUUOPs+KxYa9ahD5On8Yo/OPCi+0a0T8In+GBEQ5cmFjcvCUyzgKta2FPaiun7to/KdRcoxxTqJD4SVwooJ4u925wb2Udl8TQ0I6e0nj8ymR5yhQt8VwEqrsNeIzJ1Ukg7sGu7CtU9sHNbFW9oQhDjOAl2Rqu/FNUcYJWf1R+Z6DEED5ON8PDmdGK2YjJPECwrPe8NBVpz3zR1hOOjyhIPBNAiQ5xSlDaPm3eRNq0mUuUjIWQVGLHo8I3fHKwYG0YJvPwPl0gn+MNY55sdKc0Y0USg2dGq46zI4/SUKOL5Nzgui8usxBKOkvLf5SSIki6oXKHF7WgzyIaSM5F55w6Y2wtYBywNBCFc20gULaZdci8FIIytNFizAc/aW6TOci7WVOs/5v/UthaRq3sFO3elbRlvcoWg/lZYCfnxezKhGVApIk1vqIvDa4vToactm4S+dCPFiGXamIgIbsswMxqvMQsW+bFMg5kgHvvhJ6nDKJIHowlUW14VripMLYgj6kj/SP8+Uje1vkxDkjpnTXEZvFS9f0c7wo0mbPZ6SHhM="
